name: Generate PDF
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest    
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Check-out repository
      uses: actions/checkout@v2
      
    - name: Create PDF
      run: |
        npm install -g decktape
        sleep 2m
        export REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        decktape reveal http://wardsimon.com/${REPO_NAME} ${REPO_NAME}.pdf

    - name: Push
      env:
        GIT_USERNAME: action
        GIT_EMAIL: action@github.com
      run: |
        git config --local user.name "${{ env.GIT_USERNAME }}"
        git config --local user.email "${{ env.GIT_EMAIL }}"
        git add .
        if [[ `git status --porcelain` ]]; then
          git commit -m "Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`"
          git push
        fi
